import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavigation from '../components/BottomNavigation/BottomNavigation';
import ThemeProvider from "@/components/theme-provider/theme-provider";
import Header from "@/components/header/Header";
import { ReactQueryProvider } from "@/providers/QueryClientProvider"; // Import ReactQueryProvider
import { TokenProvider } from "@/context/TokenContext"; // Import TokenProvider
import { Toaster } from "@/components/ui/sonner"



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`font-iranYekan antialiased`}>
        <ReactQueryProvider>
          <TokenProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <Header />
              <Toaster />
              {children}
              <BottomNavigation />
            </ThemeProvider>
          </TokenProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}