
import "./globals.css";
import BottomNavigation from '../components/layout/BottomNavigation/BottomNavigation';
import ThemeProvider from "@/components/layout/theme-provider/theme-provider";
import Header from "@/components/layout/header/Header";
import { ReactQueryProvider } from "@/providers/QueryClientProvider";
import { TokenProvider } from "@/context/TokenContext"; 
import { Toaster } from "@/components/ui/sonner"
import Footer from "@/components/layout/footer/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
    <head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
    </head>
    <body className="font-iranYekan antialiased flex flex-col min-h-screen">
      <ReactQueryProvider>
        <TokenProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Header />
            <Toaster />
            <main className="flex-grow">{children}</main> 
            <Footer /> 
            <BottomNavigation />
          </ThemeProvider>
        </TokenProvider>
      </ReactQueryProvider>
    </body>
  </html>
  );
}